### ISSUE TITLE
Some sites are close

### ISSUE THREAD

**Issue by RayBB** [iRaul/awesome-portfolios#21]
I was checking out the portfolios and noticed some of the links are dead.

http://gnikoloff.com/
https://terkel.com/
http://www.samlordflavin.com/

**Comment by shahariarrabby** [comment]
http://www.guillaumejuvenet.com
http://ww1.gnikoloff.com/?subid1=7c58672c-6ccd-11e8-a2fc-a91d9af58633
https://robindelaporte.fr
