### ISSUE TITLE
consider adding http://moghya.me

### ISSUE THREAD

**Issue by moghya** [iRaul/awesome-portfolios#26]
[moghya.me](http://moghya.me) is my portfolio, all of it's content is loaded from json and no need to edit any html. Consider adding it to repo.

**Comment by TheJaredWilcurt** [comment]
Loading via JSON is a good practice, I use the same pattern on my portfolio. It makes the updating process much faster. However, I don't think this site quite meets the standards set by the other items on the list. I has a lot of bad design patterns (showing a modal on launch, distracting animated text, etc.). But keep working on your stuff.
